### ISSUE TITLE
Marquees' speed increases with amount of text 

### ISSUE THREAD

**Issue by GraefinKoks** [conradfeyt/Simple-Marquee#13]
Hello, 

I'm not sure if it's supposed to be like that, but the speed increases if there's more text in the element. 
I honestly can't figure out how to keep the speed always, no matter how many characters. 

I hope you can help. 

Greetings, 
Michelle

**Comment by conradfeyt** [comment]
Hi Michelle, 
I have added the option to adjust the speed. 
There is now a property called velocity and I would recommend passing a value between 0.1 and 0.5 but you can play with it and see what works for you
