### ISSUE TITLE
How can we add fixed speed in this

### ISSUE THREAD

**Issue by jaysingh17** [conradfeyt/Simple-Marquee#14]
How can I add fixed duration even i add more content or less content into it.

Thanks

**Comment by conradfeyt** [comment]
Hi @jaysingh17, You can set the duration as follows:
`            
let options = {
    duration: 20000,
}
$('.simple-marquee-container').SimpleMarquee(options);`

**Comment by jaysingh17** [comment]
yes But when I add multiple <li> tags into it then speed will be counted as per content i need fixed duration can you please help of me  

Thanks

**Comment by jaysingh17** [comment]
Thanks, it's working for me.

**Comment by conradfeyt** [comment]
I may be misunderstanding, but if you if the you add more or less items with a fixed duration, the speed will differ as you have more or less distance to cover in the same duration. The velocity attribute ignores duration and rather uses the speed to calculate the duration necessary. 
But I'm glad you got it working
